Add 'typename' as required to address MSVC 2015 syntax errors.
MSVC 2015 issues a bunch of syntax errors for type members of nested classes
which depend on the members of the enclosing type, e.g.:

1>cuckoohash_map.hh(1877): error C2061: syntax error: identifier 'key_type'
1>  cuckoohash_map.hh(2446): note: see reference to class template instantiation 'cuckoohash_map<Key,T,Hash,KeyEqual,Allocator,SLOT_PER_BUCKET>::locked_table' being compiled
1>  cuckoohash_map.hh(2458): note: see reference to class template instantiation 'cuckoohash_map<Key,T,Hash,KeyEqual,Allocator,SLOT_PER_BUCKET>' being compiled
1>cuckoohash_map.hh(1877): error C2238: unexpected token(s) preceding ';'
1>cuckoohash_map.hh(1878): error C2061: syntax error: identifier 'mapped_type'
1>cuckoohash_map.hh(1878): error C2238: unexpected token(s) preceding ';'
1>cuckoohash_map.hh(1879): error C2061: syntax error: identifier 'value_type'
1>cuckoohash_map.hh(1879): error C2238: unexpected token(s) preceding ';'
1>cuckoohash_map.hh(1880): error C2061: syntax error: identifier 'size_type'
1>cuckoohash_map.hh(1880): error C2238: unexpected token(s) preceding ';'
1>cuckoohash_map.hh(1881): error C2061: syntax error: identifier 'difference_type'
1>cuckoohash_map.hh(1881): error C2238: unexpected token(s) preceding ';'
1>cuckoohash_map.hh(1882): error C2061: syntax error: identifier 'hasher'
1>cuckoohash_map.hh(1882): error C2238: unexpected token(s) preceding ';'
1>cuckoohash_map.hh(1883): error C2061: syntax error: identifier 'key_equal'
1>cuckoohash_map.hh(1883): error C2238: unexpected token(s) preceding ';'
1>cuckoohash_map.hh(1884): error C2061: syntax error: identifier 'allocator_type'
1>cuckoohash_map.hh(1884): error C2238: unexpected token(s) preceding ';'
1>cuckoohash_map.hh(1885): error C2061: syntax error: identifier 'reference'
1>cuckoohash_map.hh(1885): error C2238: unexpected token(s) preceding ';'
1>cuckoohash_map.hh(1886): error C2061: syntax error: identifier 'const_reference'
1>cuckoohash_map.hh(1886): error C2238: unexpected token(s) preceding ';'
1>cuckoohash_map.hh(1887): error C2061: syntax error: identifier 'pointer'
1>cuckoohash_map.hh(1887): error C2238: unexpected token(s) preceding ';'
1>cuckoohash_map.hh(1888): error C2061: syntax error: identifier 'const_pointer'
1>cuckoohash_map.hh(1888): error C2238: unexpected token(s) preceding ';'
1>cuckoohash_map.hh(1897): error C2061: syntax error: identifier 'difference_type'
1>  cuckoohash_map.hh(2009): note: see reference to class template instantiation 'cuckoohash_map<Key,T,Hash,KeyEqual,Allocator,SLOT_PER_BUCKET>::locked_table::const_iterator' being compiled
1>cuckoohash_map.hh(1897): error C2238: unexpected token(s) preceding ';'
1>cuckoohash_map.hh(1898): error C2061: syntax error: identifier 'value_type'
1>cuckoohash_map.hh(1898): error C2238: unexpected token(s) preceding ';'
1>cuckoohash_map.hh(1899): error C2061: syntax error: identifier 'const_pointer'
1>cuckoohash_map.hh(1899): error C2238: unexpected token(s) preceding ';'
1>cuckoohash_map.hh(1900): error C2061: syntax error: identifier 'const_reference'
1>cuckoohash_map.hh(1900): error C2238: unexpected token(s) preceding ';'
1>cuckoohash_map.hh(2023): error C2061: syntax error: identifier 'pointer'
1>  cuckoohash_map.hh(2067): note: see reference to class template instantiation 'cuckoohash_map<Key,T,Hash,KeyEqual,Allocator,SLOT_PER_BUCKET>::locked_table::iterator' being compiled
1>cuckoohash_map.hh(2023): error C2238: unexpected token(s) preceding ';'
1>cuckoohash_map.hh(2024): error C2061: syntax error: identifier 'reference'
1>cuckoohash_map.hh(2024): error C2238: unexpected token(s) preceding ';'

This commit corrects the syntax by adding the typename keyword where appropriate.